# Generated by Django 3.2.5 on 2022-01-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_orderplaced_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phoneNumber',
            field=models.IntegerField(default=0, max_length=15),
        ),
    ]
